build_mat_sup/bms/urls.py
from django.urls import path

from . import views

app_name='bms'
urlpatterns = [
	path('', views.index, name='index'),
	path('itemgroupmaster/', views.itemgroup, name='itemgroup'),
	path('itemgroupmasterview/', views.itemgroupview, name='itemgroupview'),
	path('itemmaster/', views.items, name='items'),
	path('itemmasterview/', views.itemsview, name='itemsview'),
	path('lorrymaster/', views.lorry, name='lorry'),
	path('lorrymasterview/', views.lorryview, name='lorryview'),
	path('businesspartnermaster/', views.bp, name='bp'),
	path('businesspartnermasterview/', views.bpview, name='bpview'),
	path('statemaster/', views.state, name='state'),
	path('sitemaster/', views.sitemaster, name='sitemaster'),
	path('sitemasterview/', views.sitemasterview, name='sitemasterview'),
	path('businessgroupmaster/', views.businessgroup, name='businessgroup'),
	path('businessgroupmasterview/', views.businessgroupview, name='businessgroupview'),
	path('uom/', views.uom, name='uom'),
	path('uomview/', views.uomview, name='uomview'),
	path('quote/', views.quote, name='quote'),
	path('quoteview/', views.quoteview, name='quoteview'),
	path('quotedetails/', views.quotedetails, name='quotedetails'),
	path('quotedetailsview/', views.quotedetailsview, name='quotedetailsview'),
	path('companymaster/',views.companymaster, name='companymaster'),
	path('companymasterview/',views.companymasterview, name='companymasterview'),
	path('html_to_pdf_view/',views.html_to_pdf_view, name='html_to_pdf_view'),
	path('transaction/', views.transact, name='transact'),
	path('transactionview/', views.transactview, name='transactview'),
	path('export_transactions_csv/', views.export_transactions_csv, name='export_transactions_csv'),
   	path('itdelete/<pk>', views.itdelete, name='itdelete'),
   	path('itgrdelete/<pk>', views.itgrdelete, name='itgrdelete'),
	path('lorrydelete/<pk>', views.lorrydelete, name='lorrydelete'),
	path('bdelete/<pk>', views.bdelete, name='bdelete'),
	path('sitedelete/<pk>', views.sitedelete, name='sitedelete'),
	path('bgroupdelete/<pk>', views.bgroupdelete, name='bgroupdelete'),
	path('uomdelete/<pk>', views.uomdelete, name='uomdelete'),
	path('quotedelete/<pk>', views.quotedelete, name='quotedelete'),
	path('quotedetailsdelete/<pk>', views.quotedetailsdelete, name='quotedetailsdelete'),
	path('companydelete/<pk>',views.companydelete, name='companydelete'),
	path('tdelete/<pk>', views.tdelete, name='tdelete'),
]

build_mat_sup/build_mat_sup/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('bms/', include('bms.urls')),
    path('admin/', admin.site.urls),
]

build_mat_sup/bms/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class ItemGroupMaster(models.Model):
	item_group = models.CharField("Item Group Code", primary_key=True, max_length=3)
	item_group_name = models.CharField("Item Group Name", max_length=6)
	gst_rate = models.DecimalField("GST Rate", max_digits=5, decimal_places=2)	

class ItemMaster(models.Model):
	short_name = models.CharField("Short Name", primary_key=True, max_length=6)
	item_name = models.CharField("Item Name", max_length=30)
	unit_measure = models.CharField("Unit Of Measure", max_length=8)
	item_group = models.CharField("Item Group Code", max_length=3)	

class LorryMaster(models.Model):
	lorry_code = models.CharField("Lorry Code", primary_key=True, max_length=6)
	lorry_no = models.CharField("Lorry Number", max_length=14)
	driver = models.CharField("Driver Name", max_length=30)
	contact = models.CharField("Contact", max_length=15)
	tax_date = models.DateField("Tax Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")
	puc_date = models.DateField("PUC Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")
	permit_date = models.DateField("Permit Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")
	insur_date = models.DateField("Insurance Date: Enter in format 'Year(xxxx)-Month(xx)-Day(xx)'")
	length = models.DecimalField("Length of Lorry", max_digits=5, decimal_places=2)
	breadth = models.DecimalField("Breadth of Lorry", max_digits=5, decimal_places=2)

class StateMaster(models.Model):
	state_code = models.CharField("State Code", primary_key=True, max_length=2)
	state_no = models.IntegerField("State Number")
	state_name = models.CharField("State Name", max_length=30)

class BusinessPartnerMaster(models.Model):
	code = models.CharField("Code", max_length=8, null=True)
	name = models.CharField("Full name", primary_key=True, max_length=50)
	address_1 = models.CharField("Address line 1", max_length=50, null=True)
	address_2 = models.CharField("Address line 2", max_length=50, null=True)
	city = models.CharField("City", max_length=15, null=True)
	pin = models.CharField("ZIP / Postal code", max_length=6, null=True)
	state_code = models.CharField("State Code", max_length=2, null=True)
	gst_no = models.CharField("GST Number", max_length=15, null=True)
	pan_aadhar_no = models.CharField("PAN / Aadhar Number", max_length=16, null=True)
	bp_type = models.CharField("Business Partner Type", max_length=10)

class BusinessGroupMaster(models.Model):
	group_code = models.CharField("Business Group", primary_key=True, max_length=3)
	group_name = models.CharField("Group Name", max_length=45)
	group_head = models.CharField("Group Head", max_length=30)
	contact_no = models.CharField("Contact", max_length=15)

class SiteMaster(models.Model):
	site_code = models.CharField("Site Code", primary_key=True, max_length=7)
	site_name = models.CharField("Site Name", max_length=35)
	address_1 = models.CharField("Address line 1", max_length=45)
	address_2 = models.CharField("Address line 2", max_length=45)
	city = models.CharField("City", max_length=15)
	pin = models.CharField("ZIP / Postal code", max_length=6, null=True)
	state_code = models.CharField("State Code", max_length=2, null=True)
	gst_no = models.CharField("GST Number", max_length=15)
	contact_person = models.CharField("Contact Person", max_length=30)
	site_contact = models.CharField("Site Contact", max_length=15)

class UnitOfMeasureMaster(models.Model):
	uom_code = models.CharField("UOM Code", primary_key=True, max_length=8)
	uom_name = models.CharField("UOM Name", max_length=35)

class Quotation(models.Model):
	quot_no = models.CharField("Quotation Number", primary_key=True, max_length=9)
	quot_dt = models.DateField("Quotation Date")
	frm_dt = models.DateField("From Date")
	to_dt = models.DateField("To Date")
	buyer_code = models.CharField("Buyer Code", max_length=50, null=True)
	group_code = models.CharField("Business Group", max_length=3)
    
class QuotationDetails(models.Model):
	quot_no = models.CharField("Quotation Number", primary_key=True, max_length=9)
	site_code = models.CharField("Site Code", max_length=7)
	short_name = models.CharField("Item Short Name", max_length=6)
	rate = models.DecimalField("Rate of Item", max_digits=5, decimal_places=2)

class CompanyMaster(models.Model):
	company_code = models.CharField("Company Code", primary_key=True, max_length=8)
	comp_name = models.CharField("Company Name", max_length=50)
	address_1 = models.CharField("Address 1", max_length=50)
	address_2 = models.CharField("Address 2", max_length=50)
	city = models.CharField("City", max_length=30)
	pin = models.CharField("Pincode", max_length=6)
	state_code = models.CharField("State Code", max_length=2, null=True)
	phone = models.CharField("Phone", max_length=11)
	mobile = models.CharField("Mobile", max_length=10)
	gst_no = models.CharField("GST Number", max_length=15)
	pan_no = models.CharField("PAN Number", max_length=10)
	bank_name = models.CharField("Bank Name", max_length=50)
	ac_no = models.CharField("Account Number", max_length=20)
	ifsc_code = models.CharField("IFSC Code", max_length=11)
	jurisdiction = models.CharField("Jurisdiction", max_length=15)
	interest_rate = models.DecimalField("Interest Rate", max_digits=4, decimal_places=2)

#import datetime
#import uuid
#from uuid import uuid4

class Transaction(models.Model):
	tr_date = models.DateField("Transaction Date")
	#vr_no = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	vr_no = models.CharField(primary_key=True, max_length=16)
	lorry_code = models.CharField("Lorry Code", max_length=6, null=True)
	trip = models.IntegerField("Number of trips", null=True)
	challan_no = models.CharField("Challan Number", max_length=20, null=True)
	buyer = models.CharField("Buyer Name", max_length=50, null=True)
	supplier = models.CharField("Supplier Name", max_length=50, null=True)
	site_code = models.CharField("Site Code", max_length=7, null=True)
	short_name = models.CharField("Short Name", max_length=6, null=True)
	length = models.DecimalField("Length of Lorry", max_digits=5, decimal_places=2, null=True)
	breadth = models.DecimalField("Breadth of Lorry", max_digits=5, decimal_places=2, null=True)
	height = models.DecimalField("Height of Item", max_digits=5, decimal_places=2, null=True)
	quantity = models.DecimalField("Quantity of Item", max_digits=10, decimal_places=2, null=True)
	pur_rate = models.DecimalField("Pur Rate of Item", max_digits=5, decimal_places=2, null=True)
	sale_rate = models.DecimalField("Sale Rate of Item", max_digits=5, decimal_places=2, null=True)

	class Meta:
        	ordering = ['-tr_date', '-vr_no']

build_mat_sup/bms/forms.py
from django import forms
from .models import UnitOfMeasureMaster, ItemGroupMaster, StateMaster, BusinessGroupMaster, BusinessPartnerMaster, Quotation, ItemMaster, SiteMaster
#from bootstrap_datepicker.widgets import DatePicker
#from django.forms.fields import DateField

import datetime

#ItemGroupMaster
class ItemGroupForm(forms.Form):
	error_css_class = 'error'
	required_css_class = 'required'
	item_group = forms.CharField(label='ITEM GROUP', max_length=3)
	item_group_name = forms.CharField(label='ITEM GROUP NAME', max_length=6)
	gst_rate = forms.DecimalField(label='GST RATE', max_digits=5, decimal_places=2)

#ItemMaster
class ItemForm(forms.Form):
	short_name = forms.CharField(label='SHORT NAME', max_length=6)
	item_name = forms.CharField(label='ITEM NAME', max_length=30)
	unit_measure = forms.ModelChoiceField(label='UNIT OF MEASURE', queryset=UnitOfMeasureMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	item_group = forms.ModelChoiceField(label='ITEM GROUP', queryset=ItemGroupMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")

#LorryMaster
class LorryForm(forms.Form):
	lorry_code = forms.CharField(label='LORRY CODE', max_length=6)
	lorry_no = forms.CharField(label='LORRY NUMBER', max_length=14)
	driver = forms.CharField(label='DRIVER NAME', max_length=30)
	contact = forms.CharField(label='CONTACT NUMBER', max_length=15)
	tax_date = forms.DateField(label='TAX DATE', )
	puc_date = forms.DateField(label='PUC DATE', )
	permit_date = forms.DateField(label='PERMIT DATE', )
	insur_date = forms.DateField(label='INSURANCE DATE', )
	length = forms.DecimalField(label='LENGTH', max_digits=5, decimal_places=2)
	breadth = forms.DecimalField(label='BREADTH', max_digits=5, decimal_places=2)

#BusinessPartnerMaster
class BusinessPartnerForm(forms.Form):
	BP_TYPE_CHOICES = (
		('Buyer', 'Buyer'),
		('Supplier', 'Supplier'),
	)

	code = forms.CharField(label='CODE', max_length=8)
	name = forms.CharField(label='NAME', max_length=50)
	address_1 = forms.CharField(label='ADDRESS LINE 1', max_length=50)
	address_2 = forms.CharField(label='ADDRESS LINE 2', max_length=50)
	city = forms.CharField(label='CITY', max_length=15)
	pin = forms.CharField(label='PIN CODE', max_length=6)
	state_code = forms.ModelChoiceField(label='STATE CODE', queryset=StateMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	gst_no = forms.CharField(label='GST NUMBER', max_length=15)
	pan_aadhar_no = forms.CharField(label='PAN/AADHAR NUMBER', max_length=16)
	bp_type = forms.CharField(label='BUSINESS PARTNER TYPE', widget=forms.Select(choices=BP_TYPE_CHOICES))

#BusinessGroupMaster
class BusinessGroupForm(forms.Form):
	group_code = forms.CharField(label='CODE', max_length=3)
	group_name = forms.CharField(label='NAME', max_length=45)
	group_head = forms.CharField(label='GROUP HEAD', max_length=30)
	contact_no = forms.CharField(label='CONTACT NUMBER', max_length=15)

#SiteMaster
class SiteForm(forms.Form):
	site_code = forms.CharField(label='CODE', max_length=7)
	site_name = forms.CharField(label='NAME', max_length=35)
	address_1 = forms.CharField(label='ADDRESS LINE 1', max_length=45)
	address_2 = forms.CharField(label='ADDRESS LINE 2', max_length=45)
	city = forms.CharField(label='CITY', max_length=15)
	pin = forms.CharField(label='PIN CODE', max_length=6)
	state_code = forms.ModelChoiceField(label='STATE CODE', queryset=StateMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	gst_no = forms.CharField(label='GST NUMBER', max_length=15)
	contact_person = forms.CharField(label='CONTACT PERSON', max_length=30)
	site_contact = forms.CharField(label='SITE CONTACT', max_length=15)

#UnitOfMeasureMaster
class UOMForm(forms.Form):
	uom_code = forms.CharField(label='CODE', max_length=8)
	uom_name = forms.CharField(label='NAME', max_length=35)

#Quotation
class QuotationForm(forms.Form):
	quot_no = forms.CharField(label='QUOTE NUMBER', max_length=9)
	quot_dt = forms.DateField(label='QUOTE DATE', )
	frm_dt = forms.DateField(label='VALID FROM', )
	to_dt = forms.DateField(label='VALID TO', )
	buyer_code = forms.ModelChoiceField(label='BUYER', queryset=BusinessPartnerMaster.objects.values_list('pk', flat=True).filter(bp_type='buyer'), empty_label="- - - - - - SELECT - - - - - -")
	group_code = forms.ModelChoiceField(label='GROUP CODE', queryset=BusinessGroupMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")

#QuotationDetails
class QuotationDetailsForm(forms.Form):
	quot_no = forms.ModelChoiceField(label='QUOTE NUMBER', queryset=Quotation.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	site_code = forms.ModelChoiceField(label='SITE CODE', queryset=SiteMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	short_name = forms.ModelChoiceField(label='ITEM', queryset=ItemMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	rate = forms.DecimalField(label='RATE', max_digits=5, decimal_places=2)

#CompanyMaster
class CompanyForm(forms.Form):
	company_code = forms.CharField(label='COMPANY CODE', max_length=8)
	comp_name = forms.CharField(label='COMPANY NAME', max_length=50)
	address_1 = forms.CharField(label='ADDRESS LINE 1', max_length=50)
	address_2 = forms.CharField(label='ADDRESS LINE 2', max_length=50)
	city = forms.CharField(label='CITY', max_length=30)
	pin = forms.DecimalField(label='PIN CODE', max_digits=6)
	state_code = forms.ModelChoiceField(label='STATE CODE', queryset=StateMaster.objects.values_list('pk', flat=True), empty_label="- - - - - - SELECT - - - - - -")
	phone = forms.DecimalField(label='LANDLINE', max_digits=11)
	mobile = forms.DecimalField(label='MOBILE NUMBER', max_digits=10)
	gst_no = forms.CharField(label='GST NUMBER', max_length=15)
	pan_no = forms.CharField(label='PAN NUMBER', max_length=10)
	bank_name = forms.CharField(label='BANK NAME', max_length=50)
	ac_no = forms.DecimalField(label='ACCOUNT NUMBER', max_digits=20)
	ifsc_code = forms.DecimalField(label='IFSC CODE', max_digits=11)
	jurisdiction = forms.CharField(label='JURISDICTION', max_length=15)
	interest_rate = forms.DecimalField(label='INTEREST RATE', max_digits=4, decimal_places=2)

#Transaction
class TransactionForm(forms.Form):
	tr_date = forms.DateField(label='TRANSACTION DATE', initial=datetime.date.today)
	vr_no = forms.IntegerField(label='VOUCHER NUMBER', )
	lorry_code = forms.CharField(label='LORRY CODE', max_length=6)
	trip = forms.IntegerField(label='NUMBER OF TRIPS', )
	challan_no = forms.CharField(label='CHALLAN NUMBER', max_length=20)
	buyer = forms.CharField(label='BUYER', max_length=50)
	supplier = forms.CharField(label='SUPPLIER', max_length=50)
	site_code = forms.CharField(label='SITE CODE', max_length=7)
	short_name = forms.CharField(label='ITEM', max_length=6)
	length = forms.DecimalField(label='LENGTH OF LORRY', max_digits=5, decimal_places=2)
	breadth = forms.DecimalField(label='BREADTH OF LORRY', max_digits=5, decimal_places=2)
	height = forms.DecimalField(label='HEIGHT OF LORRY', max_digits=5, decimal_places=2)
	quantity = forms.DecimalField(label='QUANTITY', max_digits=10, decimal_places=2)
	pur_rate = forms.DecimalField(label='PURCHASE RATE', max_digits=5, decimal_places=2)
	sale_rate = forms.DecimalField(label='SALE RATE', max_digits=5, decimal_places=2)

build_mat_sup/bms/templates/bms/base.html
{% load widget_tweaks %}
{% load static %}
<head>
    <!--Page structure css -->
<link href="{% static 'bms/css/style.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'bms/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!--Pop Up-->
<script language="javascript" type="text/javascript">
function popitup(url) {
    var left = (screen.width - 400) / 2;
    var top = (screen.height - 200) / 4;
    newwindow=window.open(url,'{{title}}','height=200,width=400,top='+top+',left='+left);
    if (window.focus) {newwindow.focus()}
    return false;
}
</script>
  <style>
    .topnav .dropdown .dropbtn {
      font-size:11.3px;
      padding: 5px;
    }
    .topnav a {
      font-size:11.3px;
      padding: 5px;
    }
  </style>

  <div class="topnav" id="myTopnav">
  <div class="dropdown">
    <button class="dropbtn">| Item Group Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/itemgroupmaster/">Add/Update</a>
      <a href="/bms/itemgroupmasterview/">View</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Item Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/itemmaster/">Add/Update</a>
      <a href="/bms/itemmasterview/">View</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Lorry Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/lorrymaster/">Add/Update</a>
      <a href="/bms/lorrymasterview/">View</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Business Partner Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/businesspartnermaster/">Add/Update</a>
      <a href="/bms/businesspartnermasterview/">View</a>
    </div>
  </div>
    &nbsp;<a href="/bms/statemaster/">State Master |</a>
    <div class="dropdown">
    <button class="dropbtn">Site Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/sitemaster/">Add/Update</a>
      <a href="/bms/sitemasterview/">View</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Business Group Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/businessgroupmaster/">Add/Update</a>
      <a href="/bms/businessgroupmasterview/">View</a>
    </div>
  </div>
      <div class="dropdown">
    <button class="dropbtn">Unit of Measure Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/uom/">Add/Update</a>
      <a href="/bms/uomview/">View</a>
    </div>
  </div>
      <div class="dropdown">
    <button class="dropbtn">Quotation
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/quote/">Add/Update</a>
      <a href="/bms/quoteview/">View</a>
    </div>
  </div>
<div class="dropdown">
    <button class="dropbtn">Quotation Details
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/quotedetails/">Add/Update</a>
      <a href="/bms/quotedetailsview/">View</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Company Master
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/companymaster/">Add/Update</a>
      <a href="/bms/companymasterview/">View</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Transaction
      <i class="fa fa-caret-down"></i> |
    </button>
    <div class="dropdown-content">
      <a href="/bms/transaction/">Add/Update</a>
      <a href="/bms/transactionview/">View</a>
    </div>
  </div>
</div>
</head>
<body margin-top="20px" >
{% block content %}
{% endblock %}
</body>

build_mat_sup/bms/templates/bms/businessgroupmasterview.html
{% extends 'bms/base.html' %}
{% block content %}
<header>
	Business Group Master View
</header>
<article>
<table width="100%">
    <tr align="center">
        <td><b>Group Code</td>
        <td><b>Group Name</td>
        <td><b>Group Head</td>
        <td><b>Contact</td>
	<td></td>
    </tr>
    {% for item in view %}
    <tr align="center">
        <td>{{ item.group_code }}</td>
        <td>{{ item.group_name }}</td>
        <td>{{ item.group_head }}</td>
        <td>{{ item.contact_no }}</td>
	<td><a href="" onclick="return popitup('/bms/bgroupdelete/{{ item.group_code }}')">Delete</a></td>
    </tr>
    {% endfor %}
</table>
</article>
{% endblock %}

build_mat_sup/bms/templates/bms/businesspartnermaster.html
{% extends 'bms/base.html' %}
{% block content %}
<head>
<style>
	#id_bp_type {
    width: 87%;
}
</style>
</head>
<header>
	Business-Partner Master [Add New]
</header>
<center>
<article>
	<table width="40%">
	<tr align="center"><td colspan="2"><h6>[Provide Business Partner Name for updating corresponding values]</h6></td></tr>
	<form id="myForm" action="{% url 'bms:bp' %}" method="POST">
	{% csrf_token %}
		{{ form }}
		<tr><td></td><td><input type="submit" value="Submit" class="btn btn-primary"/></td></tr>
	</form>
</table>
</article>
</center>
{% endblock %}

build_mat_sup/bms/templates/bms/itemgroupmaster.html
{% extends 'bms/base.html' %}
{% block content %}
<head>
<style>
	#id_gst_rate {
    width: 91%;
}
</style>
</head>
<header>
	Item Group Master [Add New]
</header>
<center>
<article>
<table width="32%">
	<tr align="center"><td colspan="2"><h6>[Provide Item Group for updating corresponding values]</h6></td></tr>
	<form id="myForm" action="{% url 'bms:itemgroup' %}" method="POST">
	{% csrf_token %}
		{{ form }}
		<tr><td></td><td><input type="submit" value="Submit" class="btn btn-primary"/></td></tr>
	</form>
</table>
</article>
</center>
{% endblock %}

build_mat_sup/bms/templates/bms/quotation.html
{% extends 'bms/base.html' %}
{% block content %}
<!--DatePicker-->
 <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>  
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
   <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

   <script type="text/javascript">
       $(function() {
               $("#id_quot_dt").datepicker({ dateFormat: "yy-mm-dd" }).val()
       });
	$(function() {
               $("#id_frm_dt").datepicker({ dateFormat: "yy-mm-dd" }).val()
       });
	$(function() {
               $("#id_to_dt").datepicker({ dateFormat: "yy-mm-dd" }).val()
       });
   </script>
<style>
	#id_buyer_code {
    width: 70%;
}
</style>
<header>
	Quotation [Add New]
</header>
<center>
<article>
	<table width="36%">
	<tr align="center"><td colspan="2"><h6>[Provide Quotation Number for updating corresponding values]</h6></td></tr>
	<form id="myForm" action="{% url 'bms:quote' %}" method="POST">
	{% csrf_token %}
		{{ form }}
		<tr><td></td><td><input type="submit" value="Submit" class="btn btn-primary"/></td></tr>
	</form>
</table>
</article>
</center>
{% endblock %}

build_mat_sup/bms/templates/bms/uom.html
{% extends 'bms/base.html' %}
{% block content %}
<header>
	Unit Of Measure Master [Add New]
</header>
<center>
<article>
    <table width="29%">
	<tr align="center"><td colspan="2"><h6>[Provide Code for updating corresponding values]</h6></td></tr>
	<form id="myForm" action="{% url 'bms:uom' %}" method="POST">
	{% csrf_token %}
		{{ form }}
		<tr><td></td><td><input type="submit" value="Submit" class="btn btn-primary"/></td></tr>
	</form>
</table>
</article>
</center>
{% endblock %}